#!/usr/bin/env python3
"""
Weekly Scanner – Dual-Input Local Version
Location : E:\\Book\\Lister\\weekly_scanner_local.py
Schedule : Every Sunday 08:00 via Windows Task Scheduler

Two input sources, merged by ISBN, deduplicated:

  SOURCE A — booksgoat_enhanced.csv  (Playwright scraper output)
    • Has: title, isbn13, format, cost, product_url
    • No Amazon price
    • Pricing: eBay comps ONLY — skip if zero comps found
    • product_url stored in state → picked up by booksgoat_tracker.py

  SOURCE B — Merchant sheet (BOOKSGOAT_CSV_URL Google Sheet export)
    • Has: title, isbn13, cost, amazon_price
    • No product URL
    • Pricing: eBay comps first; Amazon price as FALLBACK if comps empty

  Merge rule: if ISBN appears in both, Source A wins on metadata (has
  product_url). Source B's amazon_price is grafted onto the merged record
  as a fallback in case eBay comps are unavailable.

Settings vs. previous pipeline:
  • eBay fee    15.3%   (was 13.25%)
  • Undercut    12%     (was 10%)
  • Handling    7 days  (applied to fulfillment policy on first run)
"""

import os, csv, json, time, logging, base64, re
from pathlib import Path
from datetime import datetime

import requests
import anthropic

# ── CONFIG ─────────────────────────────────────────────────────────────────────
EBAY_APP_ID        = os.environ["EBAY_APP_ID"]
EBAY_CERT_ID       = os.environ["EBAY_CERT_ID"]
EBAY_REFRESH_TOKEN = os.environ["EBAY_REFRESH_TOKEN"]
ANTHROPIC_API_KEY  = os.environ.get("ANTHROPIC_API_KEY", "")

EBAY_FEE_RATE  = 0.153    # 15.3%
UNDERCUT_PCT   = 0.12     # 12% — raise to 0.15 after 2 weeks if no sales
MIN_PROFIT     = 1.00
HANDLING_DAYS  = 7

FULFILLMENT_POLICY = "391308514023"
PAYMENT_POLICY     = "391308491023"
RETURN_POLICY      = "391308498023"
MERCHANT_LOCATION  = "home1"

BASE_DIR = Path(__file__).parent

# ── INPUT SOURCES ─────────────────────────────────────────────────────────────
# Source A: generated by scrape_booksgoat_category.py
ENHANCED_CSV_PATH = BASE_DIR / "booksgoat_enhanced.csv"

# Source B: live Google Sheet export (set BOOKSGOAT_CSV_URL in environment)
#   Columns expected: Title, ISBN-13, ISBN-10, 5 Qty (cost), Amazon Price
MERCHANT_CSV_URL  = os.environ.get("BOOKSGOAT_CSV_URL", "")
MERCHANT_CSV_PATH = BASE_DIR / "merchant_sheet_cache.csv"   # local cache

STATE_PATH = BASE_DIR / "scanner_local_state.json"
LOG_PATH   = BASE_DIR / "weekly_scanner.log"

DISCLAIMER = (
    "This item is sourced internationally to offer significant savings. "
    "Tracking information may not update until the package reaches the "
    "United States. All books are brand new, in mint condition, and "
    "carefully inspected before shipment."
)

# ── LOGGING ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    filename=str(LOG_PATH),
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger(__name__)

# ── STATE ─────────────────────────────────────────────────────────────────────
def load_state() -> dict:
    if STATE_PATH.exists():
        return json.loads(STATE_PATH.read_text(encoding="utf-8"))
    return {"listed": {}, "skipped": {}, "last_run": None}

def save_state(state: dict):
    STATE_PATH.write_text(json.dumps(state, indent=2), encoding="utf-8")

# ── AUTH ──────────────────────────────────────────────────────────────────────
def get_user_token() -> str:
    creds = base64.b64encode(f"{EBAY_APP_ID}:{EBAY_CERT_ID}".encode()).decode()
    r = requests.post(
        "https://api.ebay.com/identity/v1/oauth2/token",
        headers={
            "Authorization": f"Basic {creds}",
            "Content-Type": "application/x-www-form-urlencoded",
        },
        data=(
            "grant_type=refresh_token"
            f"&refresh_token={EBAY_REFRESH_TOKEN}"
            "&scope=https://api.ebay.com/oauth/api_scope/sell.inventory"
            " https://api.ebay.com/oauth/api_scope/sell.account"
        ),
        timeout=15,
    )
    r.raise_for_status()
    return r.json()["access_token"]

def get_app_token() -> str:
    creds = base64.b64encode(f"{EBAY_APP_ID}:{EBAY_CERT_ID}".encode()).decode()
    r = requests.post(
        "https://api.ebay.com/identity/v1/oauth2/token",
        headers={
            "Authorization": f"Basic {creds}",
            "Content-Type": "application/x-www-form-urlencoded",
        },
        data=(
            "grant_type=client_credentials"
            "&scope=https://api.ebay.com/oauth/api_scope"
        ),
        timeout=15,
    )
    r.raise_for_status()
    return r.json()["access_token"]

# ── INPUT LOADING ─────────────────────────────────────────────────────────────
def _infer_format(title: str) -> str:
    t = title.lower()
    if "hardcover"  in t: return "Hardcover"
    if "spiral"     in t: return "Spiral Bound"
    if "loose leaf" in t: return "Loose Leaf"
    return "Paperback"

def load_enhanced_csv() -> dict[str, dict]:
    """
    Source A: booksgoat_enhanced.csv produced by scrape_booksgoat_category.py
    Columns : title, isbn13, format, cost, product_url
    """
    books = {}
    if not ENHANCED_CSV_PATH.exists():
        log.warning(f"Enhanced CSV not found at {ENHANCED_CSV_PATH} — Source A skipped")
        return books

    with open(ENHANCED_CSV_PATH, "r", encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            isbn = row.get("isbn13", "").strip()
            if not isbn:
                continue
            try:
                cost = float(row.get("cost", "0").strip() or "0")
            except ValueError:
                continue
            books[isbn] = {
                "isbn":         isbn,
                "title":        row.get("title", "").strip(),
                "format":       row.get("format", "Paperback").strip(),
                "cost":         cost,
                "product_url":  row.get("product_url", "").strip(),
                "amazon_price": None,   # not available from scraper
                "source":       "enhanced",
            }

    log.info(f"Source A (enhanced CSV): {len(books)} books")
    return books


def load_merchant_sheet() -> dict[str, dict]:
    """
    Source B: BooksGoat Google Sheet export.
    Refreshes from live URL if BOOKSGOAT_CSV_URL env var is set.
    Columns : Title, ISBN-13, ISBN-10, 5 Qty (cost), Amazon Price
    """
    books = {}

    if MERCHANT_CSV_URL:
        try:
            r = requests.get(MERCHANT_CSV_URL, timeout=20)
            r.raise_for_status()
            MERCHANT_CSV_PATH.write_bytes(r.content)
            log.info("Source B: merchant sheet refreshed from Google Sheets")
        except Exception as e:
            log.warning(f"Could not refresh merchant sheet: {e} — using cache")

    if not MERCHANT_CSV_PATH.exists():
        log.warning("Merchant sheet cache not found — Source B skipped")
        return books

    with open(MERCHANT_CSV_PATH, "r", encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            isbn = row.get("ISBN-13", "").strip()
            if not isbn:
                continue
            cost_raw   = row.get("5 Qty", "").strip() or row.get("Cost", "").strip()
            amazon_raw = row.get("Amazon Price", "").strip()
            title      = row.get("Title", "").strip()
            try:
                cost = float(cost_raw) if cost_raw else 0.0
            except ValueError:
                cost = 0.0
            try:
                amazon_price = float(amazon_raw) if amazon_raw else None
            except ValueError:
                amazon_price = None

            books[isbn] = {
                "isbn":         isbn,
                "title":        title,
                "format":       _infer_format(title),
                "cost":         cost,
                "product_url":  "",
                "amazon_price": amazon_price,
                "source":       "merchant",
            }

    log.info(f"Source B (merchant sheet): {len(books)} books")
    return books


def merge_sources(enhanced: dict, merchant: dict) -> list[dict]:
    """
    Merge both dicts by ISBN.
    - Enhanced CSV wins on all metadata (title, format, cost, product_url)
    - Merchant sheet's amazon_price is grafted onto the record if available,
      so it can be used as fallback even when Source A wins
    - Books only in merchant sheet keep their amazon_price normally
    """
    merged = {}

    for isbn, book in merchant.items():
        merged[isbn] = book.copy()

    for isbn, book in enhanced.items():
        if isbn in merged:
            amazon_price = merged[isbn].get("amazon_price")  # preserve
            merged[isbn] = book.copy()
            merged[isbn]["amazon_price"] = amazon_price       # restore
            merged[isbn]["source"] = "both"
        else:
            merged[isbn] = book.copy()

    both_count     = sum(1 for b in merged.values() if b["source"] == "both")
    enhanced_only  = sum(1 for b in merged.values() if b["source"] == "enhanced")
    merchant_only  = sum(1 for b in merged.values() if b["source"] == "merchant")

    log.info(f"Merged: {len(merged)} ISBNs total  "
             f"(both={both_count}, enhanced-only={enhanced_only}, "
             f"merchant-only={merchant_only})")
    return list(merged.values())

# ── TITLE HELPERS ─────────────────────────────────────────────────────────────
def clean_title(title: str) -> str:
    title = re.sub(
        r"\s*[-–]\s*(Hardcover|Paperback|Spiral Bound|Loose Leaf)\s*$",
        "", title, flags=re.I
    )
    title = re.sub(
        r"\s*[\(\[{]?\s*ISBN[:\s]*[\d\-X]+\s*[\)\]}]?",
        "", title, flags=re.I
    )
    return title.strip(" –-")

# ── EBAY COMPS ────────────────────────────────────────────────────────────────
def get_comps(isbn: str, app_token: str) -> tuple[list[float], str]:
    headers = {
        "Authorization": f"Bearer {app_token}",
        "X-EBAY-C-MARKETPLACE-ID": "EBAY_US",
    }
    params = {
        "q": isbn,
        "category_ids": "267",
        "filter": "buyingOptions:{FIXED_PRICE},conditions:{NEW}",
        "sort": "price",
        "limit": "20",
    }
    try:
        r = requests.get(
            "https://api.ebay.com/buy/browse/v1/item_summary/search",
            headers=headers, params=params, timeout=15,
        )
        r.raise_for_status()
    except Exception as e:
        log.warning(f"Browse API error {isbn}: {e}")
        return [], "NONE"

    prices = []
    for item in r.json().get("itemSummaries", []):
        try:
            prices.append(float(item["price"]["value"]))
        except (KeyError, ValueError):
            pass

    if   len(prices) >= 3: conf = "HIGH"
    elif len(prices) >= 1: conf = "MEDIUM"
    else:                  conf = "NONE"
    return prices, conf

# ── PRICING ───────────────────────────────────────────────────────────────────
def calc_price_and_profit(
    comps: list[float],
    cost: float,
    amazon_price: float | None,
    source: str,
) -> tuple[float | None, float | None, str]:
    """
    Returns (sell_price, net_profit, method) or (None, None, 'SKIP').

    Enhanced / both  → eBay comps only (amazon_price used if grafted from
                        merchant sheet and comps are empty)
    Merchant only    → eBay comps first, then amazon_price fallback

    In all cases, if neither comps nor amazon_price is available → SKIP.
    """
    if comps:
        floor      = min(comps)
        sell_price = round(floor * (1 - UNDERCUT_PCT), 2)
        method     = "EBAY_COMP"
    elif amazon_price and source in ("merchant", "both"):
        sell_price = round(amazon_price * (1 - UNDERCUT_PCT), 2)
        method     = "AMAZON_FALLBACK"
    else:
        # Source A only (enhanced) with no comps — skip, no anchor price
        return None, None, "SKIP"

    net_profit = round(sell_price * (1 - EBAY_FEE_RATE) - cost, 2)
    return sell_price, net_profit, method

# ── AI DESCRIPTION ────────────────────────────────────────────────────────────
def generate_description(title: str, isbn: str, fmt: str) -> str:
    clean = clean_title(title)

    if not ANTHROPIC_API_KEY:
        return f"Brand new {fmt} copy of {clean} (ISBN {isbn}).\n\n{DISCLAIMER}"

    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    prompt = f"""Write a compelling, specific eBay book listing description.

Book: {clean}
ISBN: {isbn}
Format: {fmt}

Rules:
- 3–4 sentences ONLY
- Be specific about the subject and who benefits (students, clinicians, engineers, etc.)
- Mention it is a brand-new {fmt}
- Reference the edition/year if clear from the title
- Do NOT open with the book title verbatim
- Do NOT use filler like "comprehensive", "essential", "thorough", "in-depth"
- Do NOT add any disclaimer or shipping note
- Plain text only, no markdown

Output ONLY the description, nothing else."""

    try:
        resp = client.messages.create(
            model="claude-opus-4-6",
            max_tokens=300,
            messages=[{"role": "user", "content": prompt}],
        )
        body = resp.content[0].text.strip()
    except Exception as e:
        log.warning(f"Claude API error {isbn}: {e}")
        body = (f"Brand new {fmt} copy of {clean} (ISBN {isbn}). "
                "Ideal for students and professionals seeking authoritative coverage.")

    return f"{body}\n\n{DISCLAIMER}"

# ── EBAY INVENTORY ────────────────────────────────────────────────────────────
def upsert_inventory_item(isbn: str, title: str, description: str,
                          fmt: str, user_token: str) -> bool:
    headers = {
        "Authorization": f"Bearer {user_token}",
        "Content-Type": "application/json",
        "Content-Language": "en-US",
    }
    clean = clean_title(title)[:80]
    payload = {
        "product": {
            "title": clean,
            "description": description,
            "isbn": [isbn],
            "aspects": {
                "Book Title": [clean],
                "ISBN":       [isbn],
                "Format":     [fmt],
                "Language":   ["English"],
            },
        },
        "condition": "NEW",
        "conditionDescription": "Brand new, unread copy.",
        "availability": {
            "shipToLocationAvailability": {"quantity": 10}
        },
    }
    r = requests.put(
        f"https://api.ebay.com/sell/inventory/v1/inventory_item/{isbn}",
        headers=headers, json=payload, timeout=15,
    )
    if r.status_code not in (200, 204):
        log.error(f"  inventory PUT {r.status_code}: {r.text[:200]}")
        return False
    return True

def create_and_publish_offer(isbn: str, price: float,
                             user_token: str) -> tuple[str | None, str | None]:
    headers = {
        "Authorization": f"Bearer {user_token}",
        "Content-Type": "application/json",
        "Content-Language": "en-US",
    }
    payload = {
        "sku": isbn,
        "marketplaceId": "EBAY_US",
        "format": "FIXED_PRICE",
        "availableQuantity": 10,
        "categoryId": "267",
        "pricingSummary": {
            "price": {"value": f"{price:.2f}", "currency": "USD"}
        },
        "listingPolicies": {
            "fulfillmentPolicyId": FULFILLMENT_POLICY,
            "paymentPolicyId":     PAYMENT_POLICY,
            "returnPolicyId":      RETURN_POLICY,
        },
        "merchantLocationKey": MERCHANT_LOCATION,
        "tax": {"applyTax": True, "thirdPartyTaxCategory": "Books"},
    }
    r = requests.post(
        "https://api.ebay.com/sell/inventory/v1/offer",
        headers=headers, json=payload, timeout=15,
    )
    if r.status_code != 201:
        log.error(f"  offer POST {r.status_code}: {r.text[:200]}")
        return None, None

    offer_id = r.json().get("offerId")
    pub = requests.post(
        f"https://api.ebay.com/sell/inventory/v1/offer/{offer_id}/publish",
        headers=headers, timeout=15,
    )
    listing_id = pub.json().get("listingId") if pub.status_code == 200 else None
    return offer_id, listing_id

# ── FULFILLMENT POLICY (7-day handling) ───────────────────────────────────────
def ensure_7_day_handling(user_token: str):
    headers = {
        "Authorization": f"Bearer {user_token}",
        "Content-Type": "application/json",
    }
    r = requests.get(
        f"https://api.ebay.com/sell/account/v1/fulfillment_policy/{FULFILLMENT_POLICY}",
        headers=headers, timeout=15,
    )
    if r.status_code != 200:
        log.warning(f"GET fulfillment policy failed: {r.status_code}")
        return
    policy = r.json()
    if policy.get("handlingTime", {}).get("value") == HANDLING_DAYS:
        log.info("Handling time already 7d — no change needed")
        return
    policy["handlingTime"] = {"unit": "DAY", "value": HANDLING_DAYS}
    r2 = requests.put(
        f"https://api.ebay.com/sell/account/v1/fulfillment_policy/{FULFILLMENT_POLICY}",
        headers=headers, json=policy, timeout=15,
    )
    if r2.status_code in (200, 204):
        log.info(f"✓ Fulfillment policy updated → {HANDLING_DAYS}-day handling")
    else:
        log.warning(f"PUT fulfillment policy failed: {r2.status_code}")

# ── MAIN ──────────────────────────────────────────────────────────────────────
def run():
    log.info("=" * 70)
    log.info(f"Weekly scanner  fee={EBAY_FEE_RATE*100:.1f}%  "
             f"undercut={UNDERCUT_PCT*100:.0f}%  handling={HANDLING_DAYS}d")

    state      = load_state()
    listed_set = set(state.get("listed", {}).keys())

    enhanced = load_enhanced_csv()
    merchant = load_merchant_sheet()
    books    = merge_sources(enhanced, merchant)

    to_scan = [b for b in books if b["isbn"] not in listed_set]
    log.info(f"Total ISBNs: {len(books)}  |  New to scan: {len(to_scan)}")

    app_token  = get_app_token()
    user_token = get_user_token()
    ensure_7_day_handling(user_token)

    listed_count = skipped_count = error_count = 0

    for i, book in enumerate(to_scan, 1):
        isbn         = book["isbn"]
        cost         = book["cost"]
        title        = book["title"]
        fmt          = book["format"] or _infer_format(title)
        product_url  = book.get("product_url", "")
        amazon_price = book.get("amazon_price")
        source       = book["source"]

        log.info(f"[{i:3d}/{len(to_scan)}] {isbn}  src={source}  "
                 f"cost=${cost:.2f}  {title[:50]}")

        try:
            comps, conf = get_comps(isbn, app_token)
            sell_price, net_profit, method = calc_price_and_profit(
                comps, cost, amazon_price, source
            )

            if method == "SKIP":
                log.info(f"         ↳ SKIP  no comps, no amazon fallback")
                state["skipped"][isbn] = {
                    "reason": "no_price_anchor",
                    "source": source,
                    "ts":     datetime.now().isoformat(),
                }
                skipped_count += 1
                continue

            if net_profit < MIN_PROFIT:
                log.info(f"         ↳ SKIP  profit=${net_profit:.2f}  "
                         f"sell=${sell_price:.2f}  method={method}")
                state["skipped"][isbn] = {
                    "reason":     "low_profit",
                    "sell_price": sell_price,
                    "profit":     net_profit,
                    "method":     method,
                    "source":     source,
                    "ts":         datetime.now().isoformat(),
                }
                skipped_count += 1
                continue

            desc = generate_description(title, isbn, fmt)
            ok   = upsert_inventory_item(isbn, title, desc, fmt, user_token)
            if not ok:
                error_count += 1
                continue

            offer_id, listing_id = create_and_publish_offer(isbn, sell_price, user_token)
            if offer_id:
                log.info(f"         ↳ LISTED  ${sell_price:.2f}  "
                         f"profit=${net_profit:.2f}  method={method}  conf={conf}")
                state["listed"][isbn] = {
                    "offer_id":    offer_id,
                    "listing_id":  listing_id,
                    "title":       title,
                    "cost":        cost,
                    "sell_price":  sell_price,
                    "profit":      net_profit,
                    "confidence":  conf,
                    "method":      method,
                    "product_url": product_url,   # ← booksgoat_tracker.py reads this
                    "source":      source,
                    "listed_at":   datetime.now().isoformat(),
                }
                listed_count += 1
            else:
                error_count += 1

        except Exception as e:
            log.exception(f"         ↳ ERROR  {e}")
            error_count += 1

        time.sleep(0.6)

    state["last_run"] = datetime.now().isoformat()
    save_state(state)

    log.info("-" * 70)
    log.info(f"Done: {listed_count} listed | {skipped_count} skipped | "
             f"{error_count} errors")
    log.info("=" * 70)

    return listed_count, skipped_count, error_count

if __name__ == "__main__":
    run()
